# Generated by Django 3.1.3 on 2020-11-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('question', models.TextField(max_length=500)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=50, null=True)),
                ('province', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('FEMALE', 'FEMALE'), ('PREFER NOT TO SAY', 'PREFER NOT TO SAY'), ('MALE', 'MALE'), ('OTHERS', 'OTHERS')], max_length=250)),
                ('institution', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('General Public', 'General Public'), ('LGU', 'LGU'), ('Student', 'Student'), ('Academe', 'Academe'), ('SME', 'SME'), ('PWD', 'PWD')], max_length=250)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
